-- Run as BANKDB

-- Clean up existing objects if any (for fresh deployments)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BANK_USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BANK_USERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CUSTOMERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create BANK_USERS table (mainly for Employees)
CREATE TABLE BANK_USERS (
    USER_ID       NUMBER PRIMARY KEY,
    USERNAME      VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FULL_NAME     VARCHAR2(100) NOT NULL,
    EMAIL         VARCHAR2(100) UNIQUE NOT NULL,
    USER_ROLE     VARCHAR2(20) DEFAULT 'EMPLOYEE' CHECK (USER_ROLE IN ('EMPLOYEE')) NOT NULL,
    CREATED_AT    DATE DEFAULT SYSDATE NOT NULL
);

-- Create CUSTOMERS table with properties from user requirement
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID   VARCHAR2(20) PRIMARY KEY,
    FIRST_NAME    VARCHAR2(50) NOT NULL,
    LAST_NAME     VARCHAR2(50) NOT NULL,
    EMAIL         VARCHAR2(100) UNIQUE NOT NULL,
    PHONE         VARCHAR2(20) NOT NULL,
    ADDRESS       VARCHAR2(200) NOT NULL,
    DOB           DATE NOT NULL,
    NID           VARCHAR2(30) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'CLOSED')) NOT NULL,
    CREATED_DATE  DATE DEFAULT SYSDATE NOT NULL
);

-- Sequences
CREATE SEQUENCE SEQ_BANK_USERS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CUSTOMERS START WITH 1 INCREMENT BY 1 NOCACHE;

-- Trigger to handle auto-increment before insert for BANK_USERS
CREATE OR REPLACE TRIGGER TRG_BANK_USERS_BI
BEFORE INSERT ON BANK_USERS
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT SEQ_BANK_USERS.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;
END;
/

-- Trigger to handle custom format CUST-000001 for CUSTOMERS
CREATE OR REPLACE TRIGGER TRG_CUSTOMERS_BI
BEFORE INSERT ON CUSTOMERS
FOR EACH ROW
BEGIN
    IF :NEW.CUSTOMER_ID IS NULL THEN
        :NEW.CUSTOMER_ID := 'CUST-' || LPAD(SEQ_CUSTOMERS.NEXTVAL, 6, '0');
    END IF;
END;
/
