
CREATE SEQUENCE USERS_SEQ 
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE;

CREATE SEQUENCE CUSTOMER_ID_SEQ 
    START WITH 100001 
    INCREMENT BY 1 
    NOCACHE;


CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID VARCHAR2(20) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(255),
    DOB DATE,
    NID VARCHAR2(50),
    PASSWORD VARCHAR2(255) NOT NULL, 
    ROLE VARCHAR2(20) DEFAULT 'CUSTOMER' NOT NULL, 
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL, 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE TRIGGER USERS_TRG
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    
    
    :NEW.FULL_NAME := :NEW.FIRST_NAME || ' ' || :NEW.LAST_NAME;
    

    :NEW.CREATED_AT := CURRENT_TIMESTAMP;
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/
EXIT;
